"""PDF Vector Hybrid RAG retrieval facade used by internal Agents workflows."""

from __future__ import annotations

import gc
import math
import re
from collections import Counter
from dataclasses import dataclass, field
from importlib import import_module
from pathlib import Path
from typing import Any, Protocol

from app.core.settings import Settings
from app.services.pdf_rag_corpus import ROOT, read_jsonl
from app.services.pdf_rag_index import (
    DEFAULT_EMBEDDING_MODEL,
    EmbeddingClient,
    OpenAIEmbeddingClient,
    PdfRagEmbeddingError,
    diagnose_chroma_staleness,
)


# Internal backend label kept out of public API responses.
PDF_RAG_BACKEND = "pdf_vector_hybrid"

# Default validated corpus artifact generated by the build pipeline.
DEFAULT_VALIDATED_CORPUS_PATH = ROOT / "data" / "rag" / "pdf_corpus" / "validated_parent_child_chunks.jsonl"

# Default active index location; git must not track this cache.
DEFAULT_CHROMA_DIR = ROOT / ".cache" / "rag" / "chroma" / "pdf_corpus"

# Default Chroma collection name for the PDF corpus.
DEFAULT_CHROMA_COLLECTION = "pdf_rag_corpus"

# Synonym dictionary used before vector and keyword retrieval.
DEFAULT_SYNONYMS = {
    "static_obstacle_collision": ["장애물", "장애물 감지", "충돌 방지", "회피"],
    "near_miss": ["근접 위험", "안전거리", "충돌 위험"],
    "slowdown": ["감속", "속도 저감", "운행속도"],
    "crosswalk": ["횡단보도", "도로 횡단", "보행자 통행"],
    "blocked_region_violation": ["보도 통행", "통행 불가", "경로 이탈", "회피"],
    "timeout": ["시나리오 난이도", "실험 조건", "파라미터 조합"],
    "repath": ["경로 재탐색", "회피", "시나리오 난이도"],
}

# Route-specific preferred evidence sources.
ROUTE_SOURCE_PRIORITY = {
    "safety_certification": ["KOR-003", "KOR-004", "KOR-008"],
    "legal_road_operation": ["KOR-002", "KOR-008", "KOR-003", "KOR-004"],
    "crosswalk_sidewalk": ["KOR-002", "KOR-008", "KOR-003", "KOR-004"],
    "experiment_coverage": ["RSR-003", "RSR-002"],
    "scenario_generation": ["RSR-002", "RSR-004"],
    "reward_sim_to_real": ["RSR-005", "RSR-006"],
}

# Routes where research documents must not be used as top evidence.
OFFICIAL_JUDGEMENT_ROUTES = {"safety_certification", "legal_road_operation", "crosswalk_sidewalk"}

# BM25 term frequency saturation parameter for local keyword retrieval.
BM25_K1 = 1.5

# BM25 document length normalization parameter for local keyword retrieval.
BM25_B = 0.75


class PdfRagVectorIndex(Protocol):
    """Minimal vector-search interface used by the retriever facade."""

    def search(self, query: str, *, route_name: str, top_k: int) -> list[str]:
        """Return matching child chunk ids ordered by vector relevance."""


@dataclass(frozen=True)
class PdfRagRetrieverConfig:
    """Runtime limits for PDF RAG retrieval and context packing."""

    vector_top_k: int = 30
    keyword_top_k: int = 30
    context_item_limit: int = 5
    sibling_limit_per_parent: int = 2
    source_diversity_limit: int = 3
    max_context_tokens: int = 6000


@dataclass(frozen=True)
class PdfRagEvidenceItem:
    """One internal evidence item selected for LLM context or review artifacts."""

    source_id: str
    source_title: str
    source_type: str
    chunk_id: str
    parent_chunk_id: str | None
    section_title: str
    page_range: str
    evidence_text: str
    evidence_summary: str
    parent_summary: str
    topic_tags: list[str]
    use_scope: list[str]
    score: float


@dataclass(frozen=True)
class PdfRagContextPack:
    """Internal retrieval context; never expose this object directly in public API responses."""

    evidence_items: list[PdfRagEvidenceItem] = field(default_factory=list)

    def sanitized_citations(self) -> list[dict[str, str]]:
        """Return review-artifact-safe citation details without ids or scores."""
        return [
            {
                "source_title": item.source_title,
                "source_type": item.source_type,
                "page_range": item.page_range,
                "section_title": item.section_title,
                "evidence_summary": item.evidence_summary,
            }
            for item in self.evidence_items
        ]


@dataclass(frozen=True)
class PdfRagRetrievalResult:
    """Result from the PDF RAG facade with internal diagnostics."""

    available: bool
    route_name: str
    context_pack: PdfRagContextPack
    diagnostic: dict[str, Any]

    @classmethod
    def unavailable(
        cls,
        *,
        route_name: str,
        rag_error_type: str,
        embedding_error_type: str | None = None,
        detail: str | None = None,
    ) -> "PdfRagRetrievalResult":
        """Create a no-evidence result for unavailable vector RAG states."""
        diagnostic = {
            "backend": PDF_RAG_BACKEND,
            "used": False,
            "rag_unavailable": True,
            "rag_error_type": rag_error_type,
            "route_name": route_name,
            "embedding_error_type": embedding_error_type,
        }
        if detail:
            diagnostic["detail"] = detail
        return cls(
            available=False,
            route_name=route_name,
            context_pack=PdfRagContextPack(),
            diagnostic=diagnostic,
        )


class InMemoryPdfRagVectorIndex:
    """Small fake-friendly vector index that returns preconfigured chunk ids."""

    def __init__(self, results_by_query: dict[str, list[str]]) -> None:
        """Store exact-query vector hits for unit tests."""
        self.results_by_query = results_by_query

    def search(self, query: str, *, route_name: str, top_k: int) -> list[str]:
        """Return exact or substring-matched test hits."""
        _ = route_name
        if query in self.results_by_query:
            return self.results_by_query[query][:top_k]
        for stored_query, chunk_ids in self.results_by_query.items():
            if stored_query in query:
                return chunk_ids[:top_k]
        return []


class ChromaPdfRagVectorIndex:
    """Runtime Chroma vector index using query embeddings against a PersistentClient collection."""

    def __init__(
        self,
        *,
        active_dir: Path,
        collection_name: str,
        embedding_client: EmbeddingClient,
    ) -> None:
        """Store Chroma location and embedding client for runtime vector queries."""
        self.active_dir = active_dir
        self.collection_name = collection_name
        self.embedding_client = embedding_client
        self.query_count = 0
        self._cache: dict[tuple[str, str, int], list[str]] = {}

    def search(self, query: str, *, route_name: str, top_k: int) -> list[str]:
        """Embed the expanded runtime query and query Chroma for child chunk ids."""
        cache_key = (query, route_name, top_k)
        if cache_key in self._cache:
            return list(self._cache[cache_key])
        expanded_query = build_expanded_query(query)
        query_vector = self.embedding_client.embed_texts([expanded_query])[0]
        client = _create_chroma_client(self.active_dir)
        try:
            collection = client.get_collection(self.collection_name)
            self.query_count += 1
            result = collection.query(
                query_embeddings=[query_vector],
                n_results=top_k,
                where=_route_where(route_name),
                include=["metadatas", "distances"],
            )
            ids = result.get("ids") or [[]]
            chunk_ids = [str(chunk_id) for chunk_id in (ids[0] if ids else [])]
        finally:
            _close_chroma_client(client)
        self._cache[cache_key] = chunk_ids
        return list(chunk_ids)


class UnavailablePdfRagVectorIndex:
    """Vector index placeholder carrying a pre-query unavailable diagnostic."""

    def __init__(self, *, rag_error_type: str, embedding_error_type: str | None = None) -> None:
        """Store the unavailable reason detected before runtime query execution."""
        self.rag_error_type = rag_error_type
        self.embedding_error_type = embedding_error_type

    def search(self, query: str, *, route_name: str, top_k: int) -> list[str]:
        """Raise when a caller accidentally attempts to query an unavailable index."""
        _ = query, route_name, top_k
        raise RuntimeError(self.rag_error_type)


class PdfVectorHybridRagRetriever:
    """Route-aware hybrid retriever combining vector hits, keyword scoring, and parent context."""

    def __init__(
        self,
        *,
        chunks: list[dict[str, Any]] | None = None,
        vector_index: PdfRagVectorIndex | None = None,
        config: PdfRagRetrieverConfig | None = None,
        unavailable_error_type: str | None = None,
        unavailable_embedding_error_type: str | None = None,
    ) -> None:
        """Initialize the retriever with validated chunks and a vector index."""
        self.chunks = chunks or []
        self.vector_index = vector_index
        self.config = config or PdfRagRetrieverConfig()
        self.unavailable_error_type = unavailable_error_type
        self.unavailable_embedding_error_type = unavailable_embedding_error_type
        self._chunks_by_id = {str(chunk["chunk_id"]): chunk for chunk in self.chunks}
        self._children = [chunk for chunk in self.chunks if chunk.get("chunk_kind") == "child"]
        self._parents_by_id = {
            str(chunk["chunk_id"]): chunk for chunk in self.chunks if chunk.get("chunk_kind") == "parent"
        }

    def retrieve(
        self,
        query: str,
        *,
        route_hint: str | None = None,
        metrics: dict[str, Any] | None = None,
    ) -> PdfRagRetrievalResult:
        """Return internal context pack for a natural-language query."""
        _ = metrics
        route_name = route_hint or route_query(query)
        if self.unavailable_error_type:
            return PdfRagRetrievalResult.unavailable(
                route_name=route_name,
                rag_error_type=self.unavailable_error_type,
                embedding_error_type=self.unavailable_embedding_error_type,
            )
        if self.vector_index is None:
            return PdfRagRetrievalResult.unavailable(
                route_name=route_name,
                rag_error_type="chroma_index_missing",
            )
        if not self._children:
            return PdfRagRetrievalResult.unavailable(
                route_name=route_name,
                rag_error_type="validated_corpus_missing",
            )

        try:
            vector_ids = self.vector_index.search(query, route_name=route_name, top_k=self.config.vector_top_k)
        except PdfRagEmbeddingError as exc:
            return PdfRagRetrievalResult.unavailable(
                route_name=route_name,
                rag_error_type=exc.rag_error_type,
                embedding_error_type=exc.embedding_error_type,
                detail=exc.detail,
            )
        except TimeoutError:
            return PdfRagRetrievalResult.unavailable(
                route_name=route_name,
                rag_error_type="embedding_timeout",
                embedding_error_type="embedding_timeout",
            )
        except Exception as exc:
            return PdfRagRetrievalResult.unavailable(
                route_name=route_name,
                rag_error_type="chroma_query_failure",
                embedding_error_type=None,
                detail=exc.__class__.__name__,
            )

        vector_scores = {chunk_id: self.config.vector_top_k - index for index, chunk_id in enumerate(vector_ids)}
        keyword_scores = _score_keyword_hits(
            query=query,
            chunks=self._children,
            route_name=route_name,
            top_k=self.config.keyword_top_k,
        )
        merged_ids = set(vector_scores) | set(keyword_scores)
        candidates = [
            (
                _rerank_score(
                    chunk,
                    route_name=route_name,
                    vector_score=float(vector_scores.get(chunk_id, 0.0)),
                    keyword_score=float(keyword_scores.get(chunk_id, 0.0)),
                ),
                chunk,
            )
            for chunk_id in merged_ids
            if (chunk := self._chunks_by_id.get(chunk_id)) is not None and _chunk_allowed_for_route(chunk, route_name)
        ]
        candidates.sort(key=lambda item: (-item[0], str(item[1].get("chunk_id"))))
        evidence = self._build_context_pack(candidates, route_name=route_name)
        return PdfRagRetrievalResult(
            available=bool(evidence.evidence_items),
            route_name=route_name,
            context_pack=evidence,
            diagnostic={
                "backend": PDF_RAG_BACKEND,
                "used": bool(evidence.evidence_items),
                "rag_unavailable": False,
                "rag_error_type": None,
                "route_name": route_name,
                "embedding_error_type": None,
                "retrieved_chunk_count": len(evidence.evidence_items),
            },
        )

    def _build_context_pack(
        self,
        candidates: list[tuple[float, dict[str, Any]]],
        *,
        route_name: str,
    ) -> PdfRagContextPack:
        """Create a token-budgeted context pack with source diversity."""
        evidence_items: list[PdfRagEvidenceItem] = []
        per_source: dict[str, int] = {}
        per_parent: dict[str, int] = {}
        token_budget = self.config.max_context_tokens
        for score, chunk in candidates:
            source_id = str(chunk.get("source_id") or "")
            parent_id = str(chunk.get("parent_chunk_id") or "")
            if per_source.get(source_id, 0) >= self.config.source_diversity_limit:
                continue
            if parent_id and per_parent.get(parent_id, 0) >= self.config.sibling_limit_per_parent:
                continue
            item = self._to_evidence_item(chunk, score)
            estimated_tokens = max(1, math.ceil(len(item.evidence_text) / 4))
            if estimated_tokens > token_budget:
                continue
            evidence_items.append(item)
            per_source[source_id] = per_source.get(source_id, 0) + 1
            if parent_id:
                per_parent[parent_id] = per_parent.get(parent_id, 0) + 1
            token_budget -= estimated_tokens
            if len(evidence_items) >= self.config.context_item_limit:
                break
        if route_name in OFFICIAL_JUDGEMENT_ROUTES:
            evidence_items = [item for item in evidence_items if not item.source_id.startswith("RSR-")]
        return PdfRagContextPack(evidence_items=evidence_items)

    def _to_evidence_item(self, chunk: dict[str, Any], score: float) -> PdfRagEvidenceItem:
        """Convert one child chunk to internal evidence with parent summary."""
        parent_id = chunk.get("parent_chunk_id")
        parent = self._parents_by_id.get(str(parent_id)) if parent_id else None
        parent_summary = str(chunk.get("parent_summary") or (parent or {}).get("parent_summary") or "")
        page_start = chunk.get("page_start")
        page_end = chunk.get("page_end", page_start)
        page_range = str(page_start) if page_start == page_end else f"{page_start}-{page_end}"
        text = str(chunk.get("text") or "")
        return PdfRagEvidenceItem(
            source_id=str(chunk.get("source_id") or ""),
            source_title=str(chunk.get("source_title") or chunk.get("source_id") or ""),
            source_type=str(chunk.get("source_type") or ""),
            chunk_id=str(chunk.get("chunk_id") or ""),
            parent_chunk_id=str(parent_id) if parent_id else None,
            section_title=str(chunk.get("section_title") or ""),
            page_range=page_range,
            evidence_text=text,
            evidence_summary=_summarize_evidence(text),
            parent_summary=parent_summary,
            topic_tags=list(chunk.get("topic_tags") or []),
            use_scope=list(chunk.get("use_scope") or []),
            score=score,
        )


def build_expanded_query(query: str) -> str:
    """Return the query text enriched with static synonyms and Korean n-grams."""
    terms = expand_query_terms(query)
    return " ".join(terms) if terms else query


def expand_query_terms(query: str) -> list[str]:
    """Expand an English/Korean query with event synonyms and Korean n-grams."""
    terms: list[str] = []
    lowered = query.casefold()
    for token in re.findall(r"[A-Za-z0-9_가-힣/.-]+", query):
        terms.append(token)
        terms.append(token.casefold())
    for key, synonyms in DEFAULT_SYNONYMS.items():
        if key in lowered:
            terms.extend(synonyms)
    korean_parts = re.findall(r"[가-힣]{2,}", query)
    for part in korean_parts:
        terms.extend(part[index : index + 2] for index in range(max(0, len(part) - 1)))
        terms.extend(part[index : index + 3] for index in range(max(0, len(part) - 2)))
    return list(dict.fromkeys(term for term in terms if term))


def route_query(query: str) -> str:
    """Infer the retrieval route from natural-language query terms."""
    lowered = query.casefold()
    if any(token in lowered for token in ("coverage", "조합", "파라미터", "acts", "t-way")):
        return "experiment_coverage"
    if any(token in lowered for token in ("scenic", "scenario", "시나리오")):
        return "scenario_generation"
    if any(token in lowered for token in ("reward", "sim-to-real", "sim2real", "eureka")):
        return "reward_sim_to_real"
    if any(token in lowered for token in ("횡단", "crosswalk", "보도", "sidewalk")):
        return "crosswalk_sidewalk"
    if any(token in lowered for token in ("도로", "road", "법", "시행규칙")):
        return "legal_road_operation"
    return "safety_certification"


def get_pdf_rag_retriever(
    *,
    corpus_path: Path | None = None,
    chroma_dir: Path | None = None,
    embedding_client: EmbeddingClient | None = None,
    collection_name: str | None = None,
    settings: Settings | None = None,
) -> PdfVectorHybridRagRetriever:
    """Create the default PDF RAG retriever without falling back to legacy card JSONL."""
    cfg = settings or Settings()
    resolved_corpus_path = corpus_path or _resolve_agents_path(cfg.pdfRagValidatedCorpusPath)
    resolved_chroma_dir = chroma_dir or _resolve_agents_path(cfg.pdfRagChromaDir)
    resolved_collection = collection_name or DEFAULT_CHROMA_COLLECTION
    chunks = read_jsonl(resolved_corpus_path) if resolved_corpus_path.is_file() else []
    if not chunks:
        return PdfVectorHybridRagRetriever(
            chunks=[],
            vector_index=None,
            unavailable_error_type="validated_corpus_missing",
        )
    diagnostic = diagnose_chroma_staleness(
        chunk_file=resolved_corpus_path,
        active_dir=resolved_chroma_dir,
        expected_embedding_model=cfg.pdfRagEmbeddingModel or DEFAULT_EMBEDDING_MODEL,
    )
    if diagnostic.get("stale"):
        return PdfVectorHybridRagRetriever(
            chunks=chunks,
            vector_index=None,
            unavailable_error_type=str(diagnostic.get("rag_error_type") or "chroma_index_missing"),
            unavailable_embedding_error_type=diagnostic.get("embedding_error_type"),
        )
    resolved_embedding_client = embedding_client or OpenAIEmbeddingClient(
        api_key=cfg.openaiApiKey,
        model=cfg.pdfRagEmbeddingModel,
        timeout_sec=cfg.pdfRagQueryTimeoutSec,
        max_retries=cfg.pdfRagQueryMaxRetries,
    )
    return PdfVectorHybridRagRetriever(
        chunks=chunks,
        vector_index=ChromaPdfRagVectorIndex(
            active_dir=resolved_chroma_dir,
            collection_name=resolved_collection,
            embedding_client=resolved_embedding_client,
        ),
    )


def _score_keyword_hits(
    *,
    query: str,
    chunks: list[dict[str, Any]],
    route_name: str,
    top_k: int,
) -> dict[str, float]:
    """Score route-eligible child chunks with BM25 over expanded lexical terms."""
    query_terms = set(_bm25_terms(query))
    if not query_terms:
        return {}
    documents: list[tuple[dict[str, Any], Counter[str], int]] = []
    for chunk in chunks:
        if not _chunk_allowed_for_route(chunk, route_name):
            continue
        terms = _bm25_terms(str(chunk.get("text") or ""))
        if terms:
            documents.append((chunk, Counter(terms), len(terms)))
    if not documents:
        return {}

    doc_count = len(documents)
    average_doc_len = max(1.0, sum(doc_len for _, _, doc_len in documents) / doc_count)
    document_frequency = {
        term: sum(1 for _, term_counts, _ in documents if term_counts.get(term, 0) > 0) for term in query_terms
    }
    scores: list[tuple[float, str]] = []
    for chunk, term_counts, doc_len in documents:
        score = 0.0
        for term in query_terms:
            term_frequency = term_counts.get(term, 0)
            if not term_frequency:
                continue
            idf = math.log(1.0 + (doc_count - document_frequency[term] + 0.5) / (document_frequency[term] + 0.5))
            denominator = term_frequency + BM25_K1 * (1.0 - BM25_B + BM25_B * doc_len / average_doc_len)
            score += idf * (term_frequency * (BM25_K1 + 1.0)) / denominator
        if score > 0.0:
            scores.append((score, str(chunk["chunk_id"])))
    scores.sort(key=lambda item: (-item[0], item[1]))
    return {chunk_id: score for score, chunk_id in scores[:top_k]}


def _bm25_terms(text: str) -> list[str]:
    """Return repeated normalized terms used for BM25 term-frequency scoring."""
    terms: list[str] = []
    lowered = text.casefold()
    for token in re.findall(r"[A-Za-z0-9_가-힣/.-]+", text):
        terms.append(token.casefold())
    for key, synonyms in DEFAULT_SYNONYMS.items():
        if key in lowered:
            for synonym in synonyms:
                terms.extend(_bm25_terms(synonym))
    korean_parts = re.findall(r"[가-힣]{2,}", text)
    for part in korean_parts:
        terms.extend(part[index : index + 2].casefold() for index in range(max(0, len(part) - 1)))
        terms.extend(part[index : index + 3].casefold() for index in range(max(0, len(part) - 2)))
    return [term for term in terms if term]


def _chunk_allowed_for_route(chunk: dict[str, Any], route_name: str) -> bool:
    """Apply metadata route filters and official-route research blocking."""
    if chunk.get("version_status") != "active":
        return False
    if route_name not in (chunk.get("route_names") or []):
        return False
    if route_name in OFFICIAL_JUDGEMENT_ROUTES and str(chunk.get("source_id") or "").startswith("RSR-"):
        return False
    if str(chunk.get("source_id") or "") == "RSR-003":
        allowed = {"experiment_design", "coverage_gap", "next_run_recommendation"}
        if not allowed.intersection(set(chunk.get("use_scope") or [])):
            return False
    return True


def _rerank_score(
    chunk: dict[str, Any],
    *,
    route_name: str,
    vector_score: float,
    keyword_score: float,
) -> float:
    """Combine vector, keyword, authority, route priority, and source priority signals."""
    source_id = str(chunk.get("source_id") or "")
    priority_list = ROUTE_SOURCE_PRIORITY.get(route_name, [])
    priority_boost = 0.0
    if source_id in priority_list:
        priority_boost = float(len(priority_list) - priority_list.index(source_id))
    authority_rank = int(chunk.get("authority_rank") or 4)
    authority_boost = max(0.0, 5.0 - authority_rank)
    return vector_score * 1.5 + keyword_score * 6.0 + priority_boost + authority_boost


def _summarize_evidence(text: str, *, limit: int = 180) -> str:
    """Create a short internal evidence summary for review artifacts."""
    normalized = " ".join(text.split())
    return normalized if len(normalized) <= limit else normalized[: limit - 3] + "..."


def _route_where(route_name: str) -> dict[str, Any]:
    """Build Chroma metadata filters for active child chunks in one route."""
    return {
        "$and": [
            {"version_status": "active"},
            {f"route_{route_name}": True},
        ]
    }


def _resolve_agents_path(path_value: str) -> Path:
    """Resolve settings paths relative to the Agents root."""
    path = Path(path_value)
    return path if path.is_absolute() else ROOT / path


def _create_chroma_client(active_dir: Path) -> Any:
    """Create a Chroma PersistentClient for runtime retrieval."""
    chromadb_module = import_module("chromadb")
    client_type = getattr(chromadb_module, "PersistentClient")
    return client_type(path=str(active_dir))


def _close_chroma_client(client: Any) -> None:
    """Release Chroma runtime resources after each local query."""
    try:
        client.close()
    finally:
        try:
            client.clear_system_cache()
        finally:
            gc.collect()
